version: "3.8"

services:
  pgvector:
    image: pgvector/pgvector:pg16 # Official pgvector image with Postgres 16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "6024:5432" # Host:Container
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector_data:
